name: Python Scripts Test

on:
  push:
    branches:
      - main

jobs:
  test-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  
    - name: Test Python scripts
      run: |
        failed_scripts=""
        for script in 214_GAGA/*.py; do
          if ! python "$script"; then
            script_name=$(basename "$script")
            failed_scripts+=" $script_name"
          fi
        done
        if [ -n "$failed_scripts" ]; then
          echo "Error: $failed_scripts"
          exit 1
        fi